"""empty message

Revision ID: 335bc7c23a9f
Revises: 58ea5f7ba7e4
Create Date: 2023-07-27 23:14:14.362697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335bc7c23a9f'
down_revision = '58ea5f7ba7e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
