"""empty message

Revision ID: 58ea5f7ba7e4
Revises: 1cac217d2dda
Create Date: 2023-07-27 14:40:58.359680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ea5f7ba7e4'
down_revision = '1cac217d2dda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('currency')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###
