"""empty message

Revision ID: aeb5a770e6de
Revises: ecd524162943
Create Date: 2023-07-20 16:28:43.918724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb5a770e6de'
down_revision = 'ecd524162943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_update', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checked', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_checked')

    with op.batch_alter_table('trade', schema=None) as batch_op:
        batch_op.drop_column('last_update')

    # ### end Alembic commands ###
