"""empty message

Revision ID: b49edb08e88a
Revises: 85ed9e1249b9
Create Date: 2023-07-26 17:40:04.678629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b49edb08e88a'
down_revision = '85ed9e1249b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('online', sa.Boolean(), nullable=False, server_default='f'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('online')

    # ### end Alembic commands ###
