"""empty message

Revision ID: dee640a7feb8
Revises: 335bc7c23a9f
Create Date: 2023-07-31 20:39:59.620678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dee640a7feb8'
down_revision = '335bc7c23a9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('importance', sa.Integer(), nullable=False))
        batch_op.drop_constraint('wishlist_product_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('wishlist_service_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_id')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('wishlist_service_id_fkey', 'service', ['service_id'], ['id'])
        batch_op.create_foreign_key('wishlist_product_id_fkey', 'product', ['product_id'], ['id'])
        batch_op.drop_column('importance')
        batch_op.drop_column('description')

    # ### end Alembic commands ###
